spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache:  false
  datasource:
    driverClassName:  com.mysql.jdbc.Driver

